name: Generate Snake Contribution Grid
on:
  schedule:
    - cron: "0 20 * * *" # Runs daily at 8 PM UTC
  #workflow_dispatch: # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Step to generate the snake contribution grid SVG
      - name: Generate Snake SVG
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: JoviMetzger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Move the generated snake.svg to the assets/ directory
      - name: Move snake.svg to assets
        run: |
          mkdir -p assets
          mv dist/snake.svg assets/snake.svg

      # Commit and push the snake.svg file to the repository
      - name: Commit and Push Snake Grid
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add assets/snake.svg
          git commit -m "Generated Snake Grid"
          git push
