name: Generate Snake Game

# run automatically every 24 hours
on:
  schedule:
    - cron: "0 */24 * * *" 

# allows to manually run the job at any time
  workflow_dispatch:

 # run on every push on the master branch
  push:
    branches:
    - master



jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      # Generate the snake.svg file
      - name: generate github-contribution-grid-snake.svg
        uses:  Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ JoviMetzger }}  # Replace with your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Upload the result to the repository
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # The branch the file will be uploaded to
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
